Fix wait condition before running tests
Signed-off-by: rokibhasansagar <10854164+rokibhasansagar@users.noreply.github.com>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -20,8 +20,43 @@ concurrency:
   cancel-in-progress: true
 
 jobs:
+  waiter:
+    runs-on: ubuntu-latest
+    permissions:
+      actions: read
+      contents: read
+    name: Test base image rebuild
+
+    steps:
+
+      - uses: actions/checkout@v7
+        with:
+          ref: main
+          fetch-depth: 2
+
+      - name: Wait for base rebuild
+        if: ${{ github.event_name == 'push' }}
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          if ! git diff --quiet HEAD^ HEAD -- base/Dockerfile; then
+            echo "Base Dockerfile changed. Waiting for base build workflow to complete..."
+            sleep 5s
+            RUN_ID=$(gh run list --workflow "base.yml" --commit ${{ github.sha }} --json databaseId --jq '.[0].databaseId')
+            if [ -z "$RUN_ID" ] || [ "$RUN_ID" == "null" ]; then
+              echo "Error: Could not find a run for base.yml with commit ${{ github.sha }}"
+              exit 1
+            fi
+            gh run watch "$RUN_ID" --exit-status
+            echo "Base rebuild completed succesfully!"
+          fi
+
   test:
     runs-on: ubuntu-latest
+    needs: [waiter]
+    permissions:
+      actions: read
+      contents: read
     name: Test Builds
 
     strategy:
@@ -44,17 +79,10 @@ jobs:
 
     steps:
 
-      - name: Wait for base rebuild
-        if: ${{ github.event_name == 'push' }}
-        run: |
-          echo "Waiting for the Base Dockerfile to finish building"
-          for i in {1..8}; do
-            sleep 5s && echo "..."
-          done
-
       - uses: actions/checkout@v7
         with:
           ref: main
+          fetch-depth: 2
           path: action
 
       - uses: actions/checkout@v7
